---
title: "Habitat analysis"
output: 
  html_document:
    code_folding: hide
self_contained: true
---

```{r setupcomman, include = FALSE}
# globals
library(knitr)
opts_chunk$set(echo = F, message = F, warning = F)

library(tidyverse)
library(sf)
library(mapview)
library(shiny)
library(scales)
library(leaflet)
library(ggord)
library(vegan)
library(ggdendro)
library(dendextend)

# data, funcs, globals
prj <- "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs"

source('R/funcs.R')

data(habitat)
data(stream)

# map colors
cols <- mapviewGetOption("vector.palette")(4)

colgrp <- data.frame(
  Watershed = c('APT', 'PAJ', 'SLR', 'SOQ'), 
  cols = cols, 
  stringsAsFactors = F
)

# ggplot base 
pbase <- theme_bw(base_family = 'serif') +
  theme(
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank(), 
    axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size = 8), 
    axis.text.y = element_text(size = 8),
    legend.position = 'top',
    legend.direction = 'horizontal',
    # plot.margin = unit(c(4,4,0,0), "lines"),
    strip.background = element_blank(), 
    strip.text.y = element_text(angle = 0, hjust = 0, vjust = 0.5), 
    panel.background = element_rect(fill = 'black')
  ) 

# prep habitat data, long format 
habdat <- habitat %>% 
  dplyr::select(-SiteYearID, -StnNumStrt, -StnNumEnd, -HabDetail, -AssessDate) %>% 
  gather('habvar', 'habval', -Year, -SiteID, -Watershed, -geometry, -HabType)

# site, wshed lookup
siteshd <- habitat
st_geometry(siteshd) <- NULL
siteshd <- siteshd %>% 
  dplyr::select(SiteID, Watershed) %>% 
  unique %>% 
  mutate_if(is.factor, as.character)
```

<br>

The objective of these analyes is to evaluate changes in measured habitat data over time.  

Habitat measurement are taken separately at each site in different habitat types:

* __Run__
* __Riffle__
* __Pool__

Some habitat types are designated as combinations of the above.  These are ignored in the analysis unless the aggregated estimates are selected.  

```{r habinp}
selectInput("habtyp", "Choose a habitat type to evaluate:", c('run', 'riffle', 'pool', 'all'))
```

```{r habrct}
habmap <- reactive({
  
  # input
  habtyp <- input$habtyp
  
  out <- habdat %>% 
    filter(HabType %in% habtyp)
  
  return(out)
  
})

```

## Overview maps
