---
title: "Customized web-based exploration of a long-term fisheries monitoring program"
output: 
  bookdown::word_document2:
    reference_docx: my_styles.docx
urlcolor: blue
author: "Marcus W. Beck, Kristen Kittleson, Kevin O'Connor"
link-citations: true
---

Long-term monitoring programs provide critical information that informs management actions to protect, enhance, or restore natural resources.  Because these programs are resource-intensive, monitoring data are routinely evaluated to assess environmental condition and ability of the monitoring design to address management questions.  A critical challenge is the need to quickly assess status and trends from aggregated information, while preserving the ability to explore patterns in the raw data.  A twenty-year dataset of over 15000 fish density (steelhead salmon, *Oncorynchus mykiss*) and habitat measurements across four watersheds in Santa Cruz County, California was evaluated to assess resource condition and identify monitoring recommendations.  A customized, web-based analysis platform was developed using open-source software to allow managers to 1) explore status and trends, 2) evaluate spatial patterns, and 3) understand relationships between habitat and salmonid density.  The analyses were customized to address the primary management questions, while maintaining flexibility that facilitated understanding of relationships at individual sampling sites and across watershed aggregations.  This approach allowed managers to independently evaluate the datasets in a way that was not possible with conventional modes of delivering research products, such as technical reports or other hard-copy deliverables.  We suggest that interactive approaches that allow exploration of complex datasets are effective tools to evaluate long-term monitoring datasets without compromising resolution of the raw data.  We provide our approach as a proof of concept that could be used in other contexts.